### ISSUE TITLE
GCS will not build on Windows, uses non-existing <ddk/hidsdi.h>

### ISSUE THREAD

**Issue by Mischa-Alff** [TauLabs/TauLabs#993]
TauLabs will not compile on Windows 7 64bit, with MinGW 4.8.1 DW2.
It gets through a portion of the build, then fails with:
```
make[5]: Entering directory 'q:/Mischa-Alff/TauLabs/build/ground/gcs/src/plugins/rawhid'
compiling q:/Mischa-Alff/TauLabs/ground/gcs/src/plugins/rawhid/rawhidplugin.cpp
In file included from q:/Mischa-Alff/TauLabs/ground/gcs/src/plugins/rawhid/rawhid.h:39:0,
                 from q:/Mischa-Alff/TauLabs/ground/gcs/src/plugins/rawhid/rawhidplugin.h:32,
                 from q:/Mischa-Alff/TauLabs/ground/gcs/src/plugins/rawhid/rawhidplugin.cpp:28:
q:/Mischa-Alff/TauLabs/ground/gcs/src/plugins/rawhid/pjrc_rawhid.h:53:24: fatal error: ddk/hidsdi.h: No such file or directory
 #include <ddk/hidsdi.h>
                        ^
compilation terminated.
Makefile.Debug:204: recipe for target 'debug/rawhidplugin.o' failed
make[5]: *** [debug/rawhidplugin.o] Error 1
make[5]: Leaving directory 'q:/Mischa-Alff/TauLabs/build/ground/gcs/src/plugins/rawhid'
Makefile:34: recipe for target 'debug' failed
make[4]: *** [debug] Error 2
make[4]: Leaving directory 'q:/Mischa-Alff/TauLabs/build/ground/gcs/src/plugins/rawhid'
Makefile:168: recipe for target 'sub-rawhid-make_default' failed
make[3]: *** [sub-rawhid-make_default] Error 2
make[3]: Leaving directory 'q:/Mischa-Alff/TauLabs/build/ground/gcs/src/plugins'
Makefile:113: recipe for target 'sub-plugins-make_default-ordered' failed
make[2]: *** [sub-plugins-make_default-ordered] Error 2
make[2]: Leaving directory 'q:/Mischa-Alff/TauLabs/build/ground/gcs/src'
Makefile:41: recipe for target 'sub-src-make_default-ordered' failed
make[1]: *** [sub-src-make_default-ordered] Error 2
make[1]: Leaving directory 'q:/Mischa-Alff/TauLabs/build/ground/gcs'
Makefile:255: recipe for target 'gcs' failed
make: *** [gcs] Error 2
```

Disabling the plugin builds perfectly fine. The aforementioned header seems to be a w32api header. w32api stuff isn't included in all MinGW builds, and installing a new MinGW instance just for this project is a bit abnormal. (Installing w32api is a pain and doesn't work)

**Comment by mlyle** [comment]
I believe this is obsoleted from our move to QT5.  Comments?

**Comment by mlyle** [comment]
Closed-- WORKSFORME/builds on Windows with our recommended procedure.
